language:
  - objective-c 

compiler:
  - gcc
  - clang

script:
  - mkdir build
  - cd build
  - CXXFLAGS="-D__extern_always_inline=inline" cmake -DCMAKE_BUILD_TYPE=Debug -DUSE_SDL2=OFF ..
  - cmake --build .

notifications:
  irc: "irc.freenode.org#unvanquished-dev"
  on_success: change
  on_failure: always

branches:
  except:
    - debian
    - engine-upgrade/sound
